In [4]:
pip install ydata-profiling

Requirement already satisfied: ydata-profiling in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (4.17.0)
Requirement already satisfied: scipy<1.16,>=1.4.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (1.12.0)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (2.2.0)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (3.8.3)
Requirement already satisfied: pydantic>=2 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (2.13.5)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (6.0.1)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (3.1.3)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.2,>=1.16.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (1.26.4)
Requirement already satisfied: minify-html>=0.15.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.11.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.24.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (2.31.0)
Requirement already satisfied: tqdm<5,>=4.48.2 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (4.70.0)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=3 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (4.5.2)
Requirement already satisfied: imagehash==4.3.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.3 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite>=1.8 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<=0.61,>=0.56.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from imagehash==4.3.1->ydata-profiling) (1.6.0)
Requirement already satisfied: pillow in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from imagehash==4.3.1->ydata-profiling) (10.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (2.1.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.49.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (6.1.1)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from numba<=0.61,>=0.56.0->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2024.1)
Requirement already satisfied: joblib>=0.14.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.5.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (2024.2.2)
Requirement already satisfied: patsy>=0.5.6 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.3)
Requirement already satisfied: colorama in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from tqdm<5,>=4.48.2->ydata-profiling) (0.4.6)
Requirement already satisfied: importlib_metadata>=3.6 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from typeguard<5,>=3->ydata-profiling) (7.0.1)
Requirement already satisfied: typing_extensions>=4.14.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from typeguard<5,>=3->ydata-profiling) (4.16.0)
Requirement already satisfied: attrs>=19.3.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (23.2.0)
Requirement already satisfied: networkx>=2.4 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.2.1)
Requirement already satisfied: puremagic in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (1.30)
Requirement already satisfied: zipp>=0.5 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from importlib_metadata>=3.6->typeguard<5,>=3->ydata-profiling) (3.17.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.5 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from pydantic>=2->ydata-profiling) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from pydantic>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: six>=1.5 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
!pip install ipywidgets jupyter

Collecting ipywidgets
  Downloading ipywidgets-8.1.9-py3-none-any.whl.metadata (2.4 kB)
Collecting jupyter
  Downloading jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: comm>=0.1.3 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipywidgets) (0.2.1)
Requirement already satisfied: ipython>=6.1.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipywidgets) (8.18.1)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipywidgets) (5.14.1)
Collecting widgetsnbextension~=4.0.16 (from ipywidgets)
  Downloading widgetsnbextension-4.0.16-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.17 (from ipywidgets)
  Downloading jupyterlab_widgets-3.0.17-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: notebook in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter) (7.1.0)
Collecting jupyter-console (from jupyter)
  Downloading jupyter_console-6.6.3-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: nbconvert in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter) (7.16.1)
Requirement already satisfied: ipykernel in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter) (6.29.2)
Requirement already satisfied: jupyterlab in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter) (4.1.2)
Requirement already satisfied: decorator in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.17.2)
Requirement already satisfied: stack-data in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: typing-extensions in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipython>=6.1.0->ipywidgets) (4.16.0)
Requirement already satisfied: exceptiongroup in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipython>=6.1.0->ipywidgets) (1.2.0)
Requirement already satisfied: colorama in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: wcwidth in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipykernel->jupyter) (1.8.1)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipykernel->jupyter) (8.6.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipykernel->jupyter) (5.7.1)
Requirement already satisfied: nest-asyncio in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: packaging in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipykernel->jupyter) (23.2)
Requirement already satisfied: psutil in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipykernel->jupyter) (5.9.8)
Requirement already satisfied: pyzmq>=24 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipykernel->jupyter) (25.1.2)
Requirement already satisfied: tornado>=6.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from ipykernel->jupyter) (6.4)
Requirement already satisfied: importlib-metadata>=4.8.3 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-client>=6.1.12->ipykernel->jupyter) (7.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-client>=6.1.12->ipykernel->jupyter) (2.8.2)
Requirement already satisfied: zipp>=0.5 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from importlib-metadata>=4.8.3->jupyter-client>=6.1.12->ipykernel->jupyter) (3.17.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (4.2.0)
Requirement already satisfied: pywin32>=300 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (306)
Requirement already satisfied: six>=1.5 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->ipykernel->jupyter) (1.16.0)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyterlab->jupyter) (2.0.4)
Requirement already satisfied: httpx>=0.25.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyterlab->jupyter) (0.27.0)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyterlab->jupyter) (3.1.3)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyterlab->jupyter) (2.2.2)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyterlab->jupyter) (2.12.5)
Requirement already satisfied: jupyterlab-server<3,>=2.19.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyterlab->jupyter) (2.25.3)
Requirement already satisfied: notebook-shim>=0.2 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyterlab->jupyter) (0.2.4)
Requirement already satisfied: tomli in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyterlab->jupyter) (2.0.1)
Requirement already satisfied: anyio>=3.1.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (4.3.0)
Requirement already satisfied: argon2-cffi in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (23.1.0)
Requirement already satisfied: jupyter-events>=0.9.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.9.0)
Requirement already satisfied: jupyter-server-terminals in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.5.2)
Requirement already satisfied: nbformat>=5.3.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (5.9.2)
Requirement already satisfied: overrides in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (7.7.0)
Requirement already satisfied: prometheus-client in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.20.0)
Requirement already satisfied: pywinpty in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.0.12)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.18.0)
Requirement already satisfied: websocket-client in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.7.0)
Requirement already satisfied: babel>=2.10 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyterlab-server<3,>=2.19.0->jupyterlab->jupyter) (2.14.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyterlab-server<3,>=2.19.0->jupyterlab->jupyter) (0.9.17)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyterlab-server<3,>=2.19.0->jupyterlab->jupyter) (4.21.1)
Requirement already satisfied: requests>=2.31 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyterlab-server<3,>=2.19.0->jupyterlab->jupyter) (2.31.0)
Requirement already satisfied: idna>=2.8 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: certifi in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (2024.2.2)
Requirement already satisfied: httpcore==1.* in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (1.0.4)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab->jupyter) (0.14.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jinja2>=3.0.3->jupyterlab->jupyter) (2.1.5)
Requirement already satisfied: attrs>=22.2.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.19.0->jupyterlab->jupyter) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.19.0->jupyterlab->jupyter) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.19.0->jupyterlab->jupyter) (0.33.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.19.0->jupyterlab->jupyter) (0.18.0)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.0.7)
Requirement already satisfied: pyyaml>=5.3 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (6.0.1)
Requirement already satisfied: rfc3339-validator in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.1)
Requirement already satisfied: fqdn in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.5.1)
Requirement already satisfied: isoduration in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.4)
Requirement already satisfied: uri-template in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: webcolors>=1.11 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.13)
Requirement already satisfied: beautifulsoup4 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from nbconvert->jupyter) (4.12.3)
Requirement already satisfied: bleach!=5.0.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from nbconvert->jupyter) (6.1.0)
Requirement already satisfied: defusedxml in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from nbconvert->jupyter) (3.0.2)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from nbconvert->jupyter) (0.9.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from nbconvert->jupyter) (1.5.1)
Requirement already satisfied: tinycss2 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from nbconvert->jupyter) (1.2.1)
Requirement already satisfied: webencodings in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from bleach!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: fastjsonschema in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.19.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.19.0->jupyterlab->jupyter) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.19.0->jupyterlab->jupyter) (2.2.1)
Requirement already satisfied: argon2-cffi-bindings in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from argon2-cffi->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (21.2.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.16.0)
Requirement already satisfied: pycparser in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.21)
Requirement already satisfied: soupsieve>1.2 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.5)
Requirement already satisfied: arrow>=0.15.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: types-python-dateutil>=2.8.10 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.8.19.20240106)
Requirement already satisfied: executing>=1.2.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.4.1)
Requirement already satisfied: pure-eval in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.2)
Downloading ipywidgets-8.1.9-py3-none-any.whl (140 kB)
Downloading jupyterlab_widgets-3.0.17-py3-none-any.whl (217 kB)
Downloading widgetsnbextension-4.0.16-py3-none-any.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ------------------------------------- -- 2.1/2.2 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 7.4 MB/s  0:00:00
Downloading jupyter-1.1.1-py2.py3-none-any.whl (2.7 kB)
Downloading jupyter_console-6.6.3-py3-none-any.whl (24 kB)
Installing collected packages: widgetsnbextension, jupyterlab_widgets, ipywidgets, jupyter-console, jupyter

   ---------------------------------------- 0/5 [widgetsnbextension]
   -------- ------------------------------- 1/5 [jupyterlab_widgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ------------------------ --------------- 3/5 [jupyter-console]
   ------------------------ --------------- 3/5 [jupyter-console]
   ------------------------ --------------- 3/5 [jupyter-console]

In [3]:
!pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-21.0.0-cp39-cp39-win_amd64.whl.metadata (3.4 kB)
Downloading pyarrow-21.0.0-cp39-cp39-win_amd64.whl (26.2 MB)
   ---------------------------------------- 0.0/26.2 MB ? eta -:--:--
   --- ------------------------------------ 2.4/26.2 MB 12.2 MB/s eta 0:00:02
   ------- -------------------------------- 4.7/26.2 MB 11.9 MB/s eta 0:00:02
   ---------- ----------------------------- 7.1/26.2 MB 11.5 MB/s eta 0:00:02
   -------------- ------------------------- 9.4/26.2 MB 11.5 MB/s eta 0:00:02
   ----------------- ---------------------- 11.8/26.2 MB 11.5 MB/s eta 0:00:02
   --------------------- ------------------ 14.2/26.2 MB 11.5 MB/s eta 0:00:02
   ------------------------- -------------- 16.5/26.2 MB 11.3 MB/s eta 0:00:01
   ---------------------------- ----------- 18.6/26.2 MB 11.3 MB/s eta 0:00:01
   -------------------------------- ------- 21.2/26.2 MB 11.4 MB/s eta 0:00:01
   ----------------------------------- ---- 23.6/26.2 MB 11.4 MB/s eta 0:00:01
   ---------------------------------------  26.0/26.2 MB 11.4 MB/s eta 0:00:01
   ---------------------------------------  26.2/26.2 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------  26.2/26.2 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------- 26.2/26.2 MB 9.4 MB/s  0:00:02
Installing collected packages: pyarrow
Successfully installed pyarrow-21.0.0

In [8]:
pip install --upgrade typing_extensions pydantic pydantic-core

Requirement already satisfied: typing_extensions in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (4.16.0)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pydantic in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (2.13.5)
Requirement already satisfied: pydantic-core in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (2.46.5)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from pydantic) (0.7.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\stride-dev05\appdata\local\programs\python\python39\lib\site-packages (from pydantic) (0.4.2)

In [24]:
import pandas as pd
import numpy as np
from ydata_profiling import ProfileReport

In [38]:
messy_customer_df = pd.read_csv(r'C:\Users\Stride-Dev05\Downloads\Books\Python Pandas Portfolio\Messy Customer Data Cleaning\messy_customer_orders.csv')

### Profiling Data

In [11]:
profile  = ProfileReport(messy_customer_df,title="Profiling Report" , explorative = True) 
profile.to_file('report.html')
files.download()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]
  8%|▊         | 1/12 [00:03<00:34,  3.09s/it]
 17%|█▋        | 2/12 [00:04<00:18,  1.89s/it]
100%|██████████| 12/12 [00:09<00:00,  1.28it/s][A

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [12]:
# If you do not want the profiling we can go ahead with the standard data cleaning process
# After importing the dataset to a data frame five things to check
#shape of data
#checking data types dtypes
# check for null/missing  values
#Print head or tail of the dataset 
#standardizing the column names

In [72]:
messy_customer_df.shape

(51000, 12)

In [73]:
messy_customer_df.dtypes

order_id           object
customer_id        object
order_date         object
country            object
category           object
product            object
quantity            int64
unit_price         object
total_amount      float64
status             object
payment_method     object
is_returned        object
dtype: object

In [219]:
messy_customer_df.isna().sum()

order_id             0
customer_id       2033
order_date           0
country           2540
category          3052
product              0
quantity             0
unit_price        2033
total_amount      1528
status               0
payment_method       0
is_returned          0
dtype: int64

In [220]:
messy_customer_df.head()

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned
0,ORD-004208,CUST-6426,22/07/2022,canada,Clothing,Notebook Set,4,38.57,154.28,Shipped,PayPal,TRUE
1,ORD-006584,NaN,10-12-2023,NaN,NaN,Backpack,-2,NaN,NaN,Shipped,Cash,True
2,ORD-013539,NaN,26/07/2023,NaN,NaN,Travel Mug,9,NaN,NaN,Delivered,PayPal,1
3,ORD-038448,CUST-2286,02-18-2022,Germany,clothing,Bluetooth Speaker,2,192.93,385.86,shipped,Cash,No
4,ORD-022268,CUST-6074,18/06/2024,Australia,Clothing,Office Chair,5,99.7,446.80,pending,Bank Transfer,Y

In [77]:
messy_customer_df.columns = messy_customer_df.columns.str.replace(' ','_').str.lower().str.strip()

In [78]:
messy_customer_df.columns

Index(['order_id', 'customer_id', 'order_date', 'country', 'category',
       'product', 'quantity', 'unit_price', 'total_amount', 'status',
       'payment_method', 'is_returned'],
      dtype='object')

### Printing Percentage of Missing Values

In [89]:
missing = messy_customer_df.isna().mean()*100
print(missing[missing>0].sort_values(ascending=False))

category        5.984314
country         4.980392
customer_id     3.986275
unit_price      3.986275
total_amount    2.996078
dtype: float64

In [90]:
## Based on the above percentages , a point to note is if more than 40 -50 % of data is missing we need to check the data pipleline and 
##contact the relevant data engineers to understand the cause of the missing values.

### Handling Duplicates

In [93]:
#Checking for total duplicates 
messy_customer_df.duplicated().sum()

1000

In [109]:
#messy_customer_df[messy_customer_df.duplicated(keep=False).sort_values()].head(10).reset_index()
messy_customer_df[messy_customer_df['order_id']=='ORD-001282']

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned
3373,ORD-001282,CUST-0536,"May 15, 2024",AUS,BOOKS,Yoga Mat,9,£188.83,1699.47,shipped,PayPal,False
50854,ORD-001282,CUST-0536,"May 15, 2024",AUS,BOOKS,Yoga Mat,9,£188.83,1699.47,shipped,PayPal,False

In [325]:
#based on the duplicates , we need to carefully decide whether we can drop them or not 
#in this exercise i am dropping the duplicates as the line items are identical.

messy_customer_df_wo_dupes = messy_customer_df.drop_duplicates().copy()
messy_customer_df_wo_dupes.shape

(50000, 12)

### Handling Missing Values

#### Imputing Category

In [331]:
# Based on  the above missing value percentages i will now assess each and every column to understand what value i can use for imputation

messy_customer_df_wo_dupes['category'].value_counts()

category
home & garden      3240
electronics        3208
ELECTRONICS        3180
Home and Garden    3172
Home & Garden      3166
Books              3161
BOOKS              3146
Clothing           3139
SPORTS             3135
books              3110
Sports             3091
Sports             3085
clothing           3081
 clothing          3068
Electronics        3018
Name: count, dtype: int64

In [332]:
messy_customer_df_wo_dupes['category'] = messy_customer_df_wo_dupes['category'].str.lower().str.strip().str.replace('home & garden','home and garden')

In [333]:
messy_customer_df_wo_dupes['category'].value_counts()

category
home and garden    9578
books              9417
electronics        9406
sports             9311
clothing           9288
Name: count, dtype: int64

In [334]:
messy_customer_df_wo_dupes[messy_customer_df_wo_dupes['category'].isna()]

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned
1,ORD-006584,NaN,10-12-2023,NaN,NaN,Backpack,-2,NaN,NaN,Shipped,Cash,False
2,ORD-013539,NaN,26/07/2023,NaN,NaN,Travel Mug,9,NaN,NaN,Delivered,PayPal,True
5,ORD-003919,NaN,03/02/2023,NaN,NaN,Coffee Table,2,NaN,NaN,Pending,Cash,False
7,ORD-034516,CUST-5877,10/07/2022,NaN,NaN,Python Programming Book,4,208.64,834.56,Cancelled,Credit Card,False
10,ORD-003280,NaN,28/06/2022,NaN,NaN,USB Hub,7,NaN,NaN,Shipped,PayPal,False
...,...,...,...,...,...,...,...,...,...,...,...,...
48555,ORD-048990,NaN,22/12/2023,NaN,NaN,Mechanical Keyboard,8,NaN,NaN,shipped,Credit Card,True
48895,ORD-049710,NaN,2022-07-16,NaN,NaN,Wireless Headphones,2,NaN,NaN,pending,PayPal,True
49064,ORD-048788,NaN,25/05/2023,NaN,NaN,USB Hub,6,NaN,NaN,Shipped,Credit Card,False
49193,ORD-049147,NaN,2023-06-27,NaN,NaN,Backpack,9,NaN,NaN,Cancelled,Bank Transfer,False
50155,ORD-049923,NaN,12 Dec 2022,NaN,NaN,Bluetooth Speaker,2,NaN,NaN,delivered,Cash,True

In [335]:
messy_customer_df_wo_dupes['product'] = messy_customer_df_wo_dupes['product'].str.lower()

In [336]:
messy_customer_df_wo_dupes.groupby(['category','product']).size()

category  product
books     backpack               504
          bluetooth speaker      494
          coffee table           503
          desk lamp              480
          laptop stand           471
                                ...
sports    travel mug             458
          usb hub                443
          water bottle           477
          wireless headphones    464
          yoga mat               438
Length: 100, dtype: int64

In [337]:
# Basically what i am trying to do here to fill the categories  is to create a mapping tabe, categorize each product and and based on that table ,
#if the line item has that product ,we check the mapping table and then map the category.

In [338]:
# creating a category , product mapping table 

mapping_df = messy_customer_df_wo_dupes[messy_customer_df_wo_dupes['category'].notna()]
mapping_df=mapping_df[['category','product']].drop_duplicates()

# Checkign if the product is mapped to multiple categories,  if it is mapped to one category it will show 1 , if not its mapped to mulitple categories
print(mapping_df.groupby('product')['category'].nunique().sort_values(ascending=False))
mapping_df[mapping_df['product'] == 'backpack']

product
backpack                   5
bluetooth speaker          5
wireless headphones        5
water bottle               5
usb hub                    5
travel mug                 5
sunglasses                 5
running shoes              5
resistance bands           5
python programming book    5
phone case                 5
office chair               5
notebook set               5
monitor stand              5
mechanical keyboard        5
led strip lights           5
laptop stand               5
desk lamp                  5
coffee table               5
yoga mat                   5
Name: category, dtype: int64

            category   product
23          clothing  backpack
25   home and garden  backpack
48            sports  backpack
94       electronics  backpack
290            books  backpack

In [339]:
## since the products are mapped to mulitple categories , to impute this column i will fill the NaN values with "Unknown" 
messy_customer_df_wo_dupes['category'] =messy_customer_df_wo_dupes['category'].fillna('unknown')
messy_customer_df_wo_dupes['category'].isna().sum()

0

#### imputing unit price

In [364]:
## here first we will have to use regex to standardize the value formats , then we remove the white spaces and then convert to float64 datatype 
messy_customer_df_wo_dupes['unit_price'] = messy_customer_df_wo_dupes['unit_price'].str.replace(r'[$€£,]','',regex=True).str.strip().astype('float64')

In [365]:
#messy_customer_df_wo_dupes.groupby('category')['unit_price'].median()

In [366]:
messy_customer_df_wo_dupes['unit_price'] = messy_customer_df_wo_dupes['unit_price'].fillna(messy_customer_df_wo_dupes.groupby('category')['unit_price'].transform('median'))

In [367]:
messy_customer_df_wo_dupes['unit_price'].isna().sum()

0

### Imputing Amount

In [368]:
messy_customer_df_wo_dupes['total_amount'].describe()

count     50000.000000
mean       1761.368487
std        7345.361595
min       -6982.400000
25%         278.727500
50%         722.130000
75%        1379.695000
max      198564.210000
Name: total_amount, dtype: float64

In [369]:
messy_customer_df_wo_dupes['total_amount'].hist(bins=30)

In [370]:
messy_customer_df_wo_dupes['total_amount'].skew()

18.077271554573603

In [371]:
## since mean and median are very different , we will be going ahead with median imputation.

messy_customer_df_wo_dupes.groupby('category')['total_amount'].median()

category
books              693.900
clothing           690.190
electronics        671.145
home and garden    700.530
sports             687.990
unknown            722.130
Name: total_amount, dtype: float64

In [372]:
messy_customer_df_wo_dupes['total_amount'] =messy_customer_df_wo_dupes['total_amount'].fillna(messy_customer_df_wo_dupes.groupby('category')['total_amount'].transform('median'))

In [373]:
messy_customer_df_wo_dupes['total_amount'].isna().sum()

0

### Imputing Country

In [374]:
messy_customer_df_wo_dupes['country'] =messy_customer_df_wo_dupes['country'].str.strip().str.lower().str.replace('.','')

In [375]:
messy_customer_df_wo_dupes['country'].value_counts()

country
united states     11962
germany            9055
australia          8851
canada             8835
united kingdom     8797
unknown            2500
Name: count, dtype: int64

In [376]:
country_map ={

'usa' : 'united states',
'uk'  : 'united kingdom',
'de'  :  'germany',
'aus' : 'australia',
'us' : 'united states'     
}

messy_customer_df_wo_dupes['country'] = messy_customer_df_wo_dupes['country'].replace(country_map)

In [377]:
messy_customer_df_wo_dupes['country'].value_counts()

country
united states     11962
germany            9055
australia          8851
canada             8835
united kingdom     8797
unknown            2500
Name: count, dtype: int64

In [378]:
messy_customer_df_wo_dupes['country'] = messy_customer_df_wo_dupes['country'].fillna('unknown')

In [379]:
messy_customer_df_wo_dupes['country'].isna().sum()

0

### Imputing Customer ID

In [386]:
messy_customer_df_wo_dupes['customer_id'].value_counts()

customer_id
CUST-0986    17
CUST-4647    17
CUST-2682    16
CUST-1035    16
CUST-4678    15
             ..
CUST-0033     1
CUST-2831     1
CUST-0214     1
CUST-1299     1
CUST-5570     1
Name: count, Length: 7970, dtype: int64

In [387]:
messy_customer_df_wo_dupes['customer_id']=messy_customer_df_wo_dupes['customer_id'].fillna('unknown')

### Standardizing Status, Payment Method Columns

In [388]:
messy_customer_df_wo_dupes['status']=messy_customer_df_wo_dupes['status'].str.strip().str.lower()
messy_customer_df_wo_dupes['payment_method']=messy_customer_df_wo_dupes['payment_method'].str.strip().str.lower()

### Standardizing is_returned

In [389]:
messy_customer_df_wo_dupes['is_returned'].value_counts()

is_returned
False    50000
Name: count, dtype: int64

In [390]:
boolean_map = {
'FALSE' : False,
'0' : False,
'N' : False,
'no' : False,
'No': False,
'1': True,
'yes':True,
'Y' : True,
'TRUE':True ,
'Yes':True
}

messy_customer_df_wo_dupes['is_returned']= messy_customer_df_wo_dupes['is_returned'].map(boolean_map).fillna(False)

C:\Users\Stride-Dev05\AppData\Local\Temp\ipykernel_12592\4072410435.py:14: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  messy_customer_df_wo_dupes['is_returned']= messy_customer_df_wo_dupes['is_returned'].map(boolean_map).fillna(False)

In [391]:
messy_customer_df_wo_dupes['is_returned'].value_counts()

is_returned
False    50000
Name: count, dtype: int64

In [392]:
messy_customer_df_wo_dupes.isna().sum()

order_id          0
customer_id       0
order_date        0
country           0
category          0
product           0
quantity          0
unit_price        0
total_amount      0
status            0
payment_method    0
is_returned       0
dtype: int64

### Standardizing Order Date

In [401]:
messy_customer_df_wo_dupes['order_date'] = pd.to_datetime(messy_customer_df_wo_dupes['order_date'],dayfirst=False,errors='coerce')
failed = messy_customer_df_wo_dupes['order_date'].isnull().sum()
print(failed)

37544

In [402]:
messy_customer_df_wo_dupes.head()

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned
0,ORD-004208,CUST-6426,2022-07-22,canada,clothing,notebook set,4,38.57,154.28,shipped,paypal,False
1,ORD-006584,unknown,NaT,unknown,unknown,backpack,-2,168.46,722.13,shipped,cash,False
2,ORD-013539,unknown,2023-07-26,unknown,unknown,travel mug,9,168.46,722.13,delivered,paypal,False
3,ORD-038448,CUST-2286,NaT,germany,clothing,bluetooth speaker,2,192.93,385.86,shipped,cash,False
4,ORD-022268,CUST-6074,2024-06-18,australia,clothing,office chair,5,99.70,446.80,pending,bank transfer,False

### Feature Engineering

In [412]:
messy_customer_df_wo_dupes['order_year'] =messy_customer_df_wo_dupes['order_date'].dt.year.astype('Int64')
messy_customer_df_wo_dupes['order_month']= messy_customer_df_wo_dupes['order_date'].dt.month.astype('Int64')
messy_customer_df_wo_dupes['order_day_of_week'] = messy_customer_df_wo_dupes['order_date'].dt.day_name()

In [413]:
messy_customer_df_wo_dupes.head()

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned,order_year,order_month,order_day_of_week
0,ORD-004208,CUST-6426,2022-07-22,canada,clothing,notebook set,4,38.57,154.28,shipped,paypal,False,2022,7,Friday
1,ORD-006584,unknown,NaT,unknown,unknown,backpack,-2,168.46,722.13,shipped,cash,False,<NA>,<NA>,NaN
2,ORD-013539,unknown,2023-07-26,unknown,unknown,travel mug,9,168.46,722.13,delivered,paypal,False,2023,7,Wednesday
3,ORD-038448,CUST-2286,NaT,germany,clothing,bluetooth speaker,2,192.93,385.86,shipped,cash,False,<NA>,<NA>,NaN
4,ORD-022268,CUST-6074,2024-06-18,australia,clothing,office chair,5,99.70,446.80,pending,bank transfer,False,2024,6,Tuesday

In [414]:
## Here there are some amounts where the quantity is negative but the total amount is positive ,this means that there is some erroreous data in the total amount column, to address 
#this issue we will calculate , new total amount column = quantity * unitprice
messy_customer_df_wo_dupes['new_total_amount'] = messy_customer_df_wo_dupes['quantity'] * messy_customer_df_wo_dupes['unit_price']

In [420]:
## Another important thing to check is the line items that have negative quantities ( i.e quantity <=0 )  - > based on this we either remove or replace the quantities .

messy_customer_df_wo_dupes.loc[messy_customer_df_wo_dupes['quantity'] <= 0 ]

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned,order_year,order_month,order_day_of_week,new_total_amount
1,ORD-006584,unknown,NaT,unknown,unknown,backpack,-2,168.46,722.13,shipped,cash,False,<NA>,<NA>,NaN,-336.92
193,ORD-040428,CUST-4374,NaT,united states,sports,resistance bands,0,258.43,0.00,cancelled,credit card,False,<NA>,<NA>,NaN,0.00
306,ORD-029737,unknown,2022-11-25,unknown,unknown,yoga mat,-3,168.46,722.13,cancelled,paypal,False,2022,11,Friday,-505.38
449,ORD-049440,CUST-1197,NaT,canada,home and garden,phone case,0,1212.28,0.00,delivered,credit card,False,<NA>,<NA>,NaN,0.00
638,ORD-013603,CUST-1033,NaT,united states,sports,yoga mat,0,110.68,0.00,cancelled,cash,False,<NA>,<NA>,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50364,ORD-021365,CUST-3272,NaT,germany,home and garden,led strip lights,0,1264.40,0.00,shipped,cash,False,<NA>,<NA>,NaN,0.00
50446,ORD-032321,CUST-3893,2022-08-11,germany,home and garden,sunglasses,-3,179.77,-539.31,shipped,cash,False,2022,8,Thursday,-539.31
50576,ORD-025548,CUST-5050,2022-04-20,australia,sports,mechanical keyboard,-4,18.39,-73.56,delivered,bank transfer,False,2022,4,Wednesday,-73.56
50695,ORD-038361,CUST-4953,NaT,canada,home and garden,phone case,-1,213.67,-213.67,delivered,cash,False,<NA>,<NA>,NaN,-213.67
50923,ORD-033764,CUST-3766,NaT,united kingdom,sports,monitor stand,0,256.47,0.00,pending,bank transfer,False,<NA>,<NA>,NaN,0.00